### ISSUE TITLE
confirm dApp confirms DOI but cannot write to blockchain nor notify sendDapp

### ISSUE THREAD

**Issue by inspiraluna** [Doichain/dapp#44]
rror: 'jobs.blockchain.update.exception',
I20180717-16:47:36.494(2)?   reason: 
I20180717-16:47:36.495(2)?    { Error: ClientError: Host is required [doichain.update.exception]
I20180717-16:47:36.495(2)?     at update (imports/modules/server/doichain/update.js:66:11)
I20180717-16:47:36.495(2)?     at JobQueue.worker (server/api/blockchain_jobs.js:23:5)
I20180717-16:47:36.496(2)?     at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:191:8)
I20180717-16:47:36.496(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180717-16:47:36.497(2)?     at packages/meteor.js:505:25
I20180717-16:47:36.497(2)?     at runWithEnvironment (packages/meteor.js:1241:24)
I20180717-16:47:36.497(2)?      isClientSafe: true,
I20180717-16:47:36.498(2)?      error: 'doichain.update.exception',
I20180717-16:47:36.498(2)?      reason: 
I20180717-16:47:36.498(2)?       { ClientError: Host is required
I20180717-16:47:36.498(2)?     at /usr/src/doichain/dapp/node_modules/simpl-schema/dist/SimpleSchema.js:742:21
I20180717-16:47:36.499(2)?     at Array.forEach (<anonymous>)
I20180717-16:47:36.499(2)?     at SimpleSchema.validate (/usr/src/doichain/dapp/node_modules/simpl-schema/dist/SimpleSchema.js:730:15)
I20180717-16:47:36.499(2)?     at update (imports/modules/server/doichain/update.js:31:18)
I20180717-16:47:36.499(2)?     at JobQueue.worker (server/api/blockchain_jobs.js:23:5)
I20180717-16:47:36.499(2)?     at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:191:8)
I20180717-16:47:36.500(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180717-16:47:36.500(2)?     at packages/meteor.js:505:25
I20180717-16:47:36.500(2)?     at runWithEnvironment (packages/meteor.js:1241:24)
I20180717-16:47:36.500(2)?         errorType: 'ClientError',
I20180717-16:47:36.500(2)?         name: 'ClientError',
I20180717-16:47:36.501(2)?         error: 'validation-error',
I20180717-16:47:36.501(2)?         details: [Array] },
I20180717-16:47:36.501(2)?      details: undefined,
I20180717-16:47:36.501(2)?      message: 'ClientError: Host is required [doichain.update.exception]',
I20180717-16:47:36.501(2)?      errorType: 'Meteor.Error' },

it looks like confirm dApp cannot extract the host.

**Comment by inspiraluna** [comment]
{
  "status": "fail",
  "message": "Error: Confirmed by must be a valid IPv4 or IPv6 address in opt-ins update [opt-ins.confirm.exception]"
}
